version: '3.8'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker_1
      - broker_2
      - broker_3
    ports:
      - "8081:8081"
    networks:
      - kafka_net
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker_1:29090,broker_2:29091,broker_3:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: backward
    command: /bin/sh -c "./script.sh && <comando_original_del_schema_registry>"
    volumes:
      - ./script.sh:/script.sh:ro

networks:
  kafka_net:
    name: network_kafka_conexion
